version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_local
    environment:
      POSTGRES_USER: springboot_user
      POSTGRES_PASSWORD: springboot_password
      POSTGRES_DB: springboot_db
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: JobPortalApp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobportal
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "8080:8080"
